use mapco;

CREATE TABLE AbonoDetalle (
	IdAbonoDetalle int NOT NULL AUTO_INCREMENT,
	IdAbono int NULL,
	IdVenta int NULL,
	IdSucursal int NOT NULL,
	IdDctoSolicitud int NULL,
	IdDctoSolicitudDetalle int NULL,
	ImportePagado decimal(18, 2) NULL,
	ImporteImpuesto decimal(18, 2) NULL,
	ImporteTotal decimal(18, 2) NULL,
	ImporteDctoTotal decimal(18, 2) NULL,
	ImporteSaldoAnterior decimal(18, 2) NULL,
	ImporteSaldoInsoluto decimal(18, 2) NULL,
	Parcialidad int NULL,
	FECHAINSERT datetime NOT NULL,
	USUARIOINSERT int NOT NULL,
	FECHAUPDATE datetime NULL,
	USUARIOUPDATE int NULL,
	FECHABAJA datetime NULL,
	USUARIOBAJA int NULL,
	ESTATUS bit NOT NULL,
	TipoMovimiento varchar(2) NULL,
	Folio varchar(6) NULL,
	Fecha date NULL,
	Registro nchar(10) NULL,
	TipoMovimientoVta varchar(2) NULL,
	FolioVta varchar(6) NULL,
	FechaVta date NULL,
	RegistroVta int NULL,
	IdCliente int NULL,
	IdCargo int NULL,
	TCNumeroCuenta varchar(20) NULL,
	IdInteres int NULL,
	PagoInicialTC bit NULL,
	FECHAGENERADOTC datetime NULL,
	GeneradoManualTC bit NULL,
	MigradoDxC bit NULL,
	PRIMARY KEY (IdAbonoDetalle)
)