use mapco;

CREATE TABLE DispositivosComunicacion (
	idComunicacion int NOT NULL AUTO_INCREMENT,
	idSucursal int NOT NULL,
	idUsuario int NOT NULL,
	idTipo int NULL,
	idError int NULL,
	TicketBI LONG NULL,
	Ticket varchar(4000) NULL,
	NumTarjeta varchar(16) NULL,
	MensajeLDI varchar(4000) NULL,
	NumeroLDI int NULL,
	Importe decimal(18, 2) NULL,
	FECHAINSERT datetime NOT NULL,
	FECHAUPDATE datetime NULL,
	ESTATUS bit NULL,
	NumCuenta varchar(30) NULL,
	idComunicacionRel int NULL,
	IdCliente int NULL,
	Autorizacion varchar(20) NULL,
	Referencia varchar(50) NULL,
	FechaHora datetime NULL,
	ImporteCobrado decimal(18, 2) NULL,
	Voucher varchar(4000) NULL,
	AUTOCODE varchar(50) NULL,
	ARRAYRESPUESTA varchar(4000) NULL,
	IDCAJA int NULL,
	NCONTROL varchar(50) NULL,
	idErrorCancela int NULL,
	Cancelada bit NULL,
	FECHACANCELA datetime NULL,
	AutorizacionCancela varchar(50) NULL,
	AutoCodeCancela varchar(50) NULL,
	VoucherCancela varchar(4000) NULL,
	NControlCancela varchar(50) NULL,
	ArrayRespuestaCancela varchar(4000) NULL,
	MensajeLDICancela varchar(4000) NULL,
	ReferenciaCancela varchar(50) NULL,
	idVenta int NULL,
	idAbono int NULL,
    PRIMARY KEY (idComunicacion)
)